<?xml version="1.0"?>
<package format="3">
  <name>test_pipeline</name>
  <version>0.0.0</version>
  <description>Waypoint client for ORCA</description>

  <maintainer email="your@email.com">your_name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>vortex_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>